/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package capanyilvantarto;

import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

/**
 *
 * @author zsenakistvan
 */
public class Ablak extends javax.swing.JFrame {
private List<Capa> capak = new ArrayList<>();
    /**
     * Creates new form Ablak
     */
private static int[] enabled = {1, 1, 1, 1}; 
    public Ablak() {
        initComponents();
        
        try{
            File f = new File("capak.xml");
            DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
            DocumentBuilder builder = dbf.newDocumentBuilder();
            Document xml = builder.parse(f);
            xml.normalize();
            NodeList capaNodes = xml.getElementsByTagName("capa");
            this.cbCapak.addItem("Válasszon!");
            for(int i = 0; i < capaNodes.getLength(); i++){
                Node node = capaNodes.item(i);
                Element capa = (Element)node;
                this.cbCapak.addItem(capa.getElementsByTagName("nev").item(0).getTextContent());
            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
        
        
        
        
        Capa Capeti = new Capa("Capeti", 5, CapaFaj.TIGRISCAPA, 3.0, "Zöld foki szigetek");
        Capa Capali = new Capa("Capali", 7, CapaFaj.MACSKACAPA, 0.7, "Egyiptom");
        Capa Fogas = new Capa("Fogas", 10, CapaFaj.FEHERCAPA, 7.0, "Vörös Tenger");
        Capa Fina = new Capa("Fina", 2, CapaFaj.TIGRISCAPA, 2.5, "Mexikói Öböl");
        
        
        this.capak.add(Fina);
        this.capak.add(Fogas);
        this.capak.add(Capali);
        this.capak.add(Capeti);
        for(Capa capa : this.capak){
            //this.cbCapak.addItem(capa.getNev());
        }
        
        this.jPanel1.setVisible(false);
        this.btnNevMent.setVisible(false);
        this.txtNevSzerk.setVisible(false);
        this.spHossz.setVisible(false);
        this.btnMentHossz.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAblak = new javax.swing.JPanel();
        btnUdv = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbCapak = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblNev = new javax.swing.JLabel();
        lblKor = new javax.swing.JLabel();
        lblFaj = new javax.swing.JLabel();
        lblHossz = new javax.swing.JLabel();
        lblLakhely = new javax.swing.JLabel();
        btnSzerkeszt = new javax.swing.JButton();
        txtNevSzerk = new javax.swing.JTextField();
        btnNevMent = new javax.swing.JButton();
        spHossz = new javax.swing.JSpinner();
        btnSzerkesztHossz = new javax.swing.JButton();
        btnMentHossz = new javax.swing.JButton();
        btnSzulinap = new javax.swing.JButton();
        pbEnergia = new javax.swing.JProgressBar();
        btnEszik = new javax.swing.JButton();
        spKcal = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnUdv.setText("Köszöntés");
        btnUdv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUdv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUdvMouseClicked(evt);
            }
        });

        jLabel1.setText("Az alábbi cápákat tartjuk számon:");

        cbCapak.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbCapakItemStateChanged(evt);
            }
        });
        cbCapak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCapakActionPerformed(evt);
            }
        });

        jLabel2.setText("Név: ");

        jLabel3.setText("Kor:");

        jLabel4.setText("Faj:");

        jLabel5.setText("Hossz:");

        jLabel6.setText("Lakhely:");

        lblNev.setText("jLabel7");

        lblKor.setText("jLabel8");

        lblFaj.setText("jLabel9");

        lblHossz.setText("jLabel10");

        lblLakhely.setText("jLabel11");

        btnSzerkeszt.setText("Szerkesztés");
        btnSzerkeszt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSzerkesztMouseClicked(evt);
            }
        });

        btnNevMent.setText("Mentés");
        btnNevMent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNevMentMouseClicked(evt);
            }
        });

        spHossz.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1000, 1));

        btnSzerkesztHossz.setText("Szerkesztés");
        btnSzerkesztHossz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSzerkesztHosszMouseClicked(evt);
            }
        });

        btnMentHossz.setText("Mentés");
        btnMentHossz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMentHosszMouseClicked(evt);
            }
        });

        btnSzulinap.setLabel("Kor++");
        btnSzulinap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSzulinapMouseClicked(evt);
            }
        });

        pbEnergia.setMinimum(1);
        pbEnergia.setValue(50);

        btnEszik.setText("Eszik");
        btnEszik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEszikMouseClicked(evt);
            }
        });

        spKcal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spKcalStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pbEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNev)
                            .addComponent(lblLakhely)
                            .addComponent(lblHossz)
                            .addComponent(lblFaj)
                            .addComponent(lblKor))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNevSzerk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spHossz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSzerkeszt)
                                    .addComponent(btnSzerkesztHossz))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnMentHossz)
                                    .addComponent(btnNevMent)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSzulinap)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(spKcal, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnEszik)
                .addGap(185, 185, 185))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblNev)
                    .addComponent(btnSzerkeszt)
                    .addComponent(txtNevSzerk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNevMent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblKor)
                    .addComponent(btnSzulinap))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblFaj))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblHossz)
                    .addComponent(spHossz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSzerkesztHossz)
                    .addComponent(btnMentHossz))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblLakhely))
                .addGap(55, 55, 55)
                .addComponent(pbEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEszik)
                    .addComponent(spKcal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlAblakLayout = new javax.swing.GroupLayout(pnlAblak);
        pnlAblak.setLayout(pnlAblakLayout);
        pnlAblakLayout.setHorizontalGroup(
            pnlAblakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAblakLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(cbCapak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAblakLayout.createSequentialGroup()
                .addContainerGap(349, Short.MAX_VALUE)
                .addGroup(pnlAblakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAblakLayout.createSequentialGroup()
                        .addComponent(btnUdv)
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAblakLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        pnlAblakLayout.setVerticalGroup(
            pnlAblakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAblakLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnUdv)
                .addGap(37, 37, 37)
                .addGroup(pnlAblakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbCapak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAblak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAblak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUdvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUdvMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Üdvözlünk a Cápa nyilvántartóban!");
    }//GEN-LAST:event_btnUdvMouseClicked

    private void cbCapakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCapakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCapakActionPerformed

    private void cbCapakItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbCapakItemStateChanged
        // TODO add your handling code here:
        if(this.cbCapak.getSelectedIndex() != 0){
            this.jPanel1.setVisible(true);
            this.lblNev.setText(this.capak.get(this.cbCapak.getSelectedIndex() - 1).getNev());
            //Integer index = this.cbCapak.getSelectedIndex() - 1;
            //Capa c = this.capak.get(index);
            //String nev = c.getNev();
            //this.lblNev.setText(nev);
            this.lblFaj.setText(this.capak.get(this.cbCapak.getSelectedIndex() - 1).getFaj().toString());
            this.lblHossz.setText(this.capak.get(this.cbCapak.getSelectedIndex() - 1).getHossz().toString());
            this.lblKor.setText(this.capak.get(this.cbCapak.getSelectedIndex() - 1).getKor().toString());
            this.lblLakhely.setText(this.capak.get(this.cbCapak.getSelectedIndex() - 1).getLakhely());
        }
        else{
            this.jPanel1.setVisible(false);
        }
        this.btnSzulinap.setEnabled(true);
    }//GEN-LAST:event_cbCapakItemStateChanged

    private void btnSzerkesztMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSzerkesztMouseClicked
        // TODO add your handling code here:
        this.btnNevMent.setVisible(true);
        this.btnSzerkeszt.setVisible(false);
        this.txtNevSzerk.setVisible(true);
        this.txtNevSzerk.setText(this.cbCapak.getSelectedItem().toString());
        this.lblNev.setVisible(false);
        this.txtNevSzerk.setLocation(this.lblNev.getLocation());
        
    }//GEN-LAST:event_btnSzerkesztMouseClicked

    private void btnNevMentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNevMentMouseClicked
        // TODO add your handling code here:
        this.lblNev.setText(this.txtNevSzerk.getText());
        this.lblNev.setVisible(true);
        this.txtNevSzerk.setVisible(false);
        this.btnSzerkeszt.setVisible(true);
        this.btnNevMent.setVisible(false);
        Capa c = this.capak.get(this.cbCapak.getSelectedIndex() - 1);
        c.setNev(this.txtNevSzerk.getText());
        this.capak.set(this.cbCapak.getSelectedIndex() - 1, c);
        this.cbCapak.insertItemAt(c.getNev(), this.cbCapak.getSelectedIndex());
        this.cbCapak.removeItemAt(this.cbCapak.getSelectedIndex());
        
        
        
    }//GEN-LAST:event_btnNevMentMouseClicked

    private void btnSzerkesztHosszMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSzerkesztHosszMouseClicked
        // TODO add your handling code here:
        this.btnSzerkesztHossz.setVisible(false);
        this.btnMentHossz.setVisible(true);
        this.spHossz.setVisible(true);
        
        
    }//GEN-LAST:event_btnSzerkesztHosszMouseClicked

    private void btnMentHosszMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMentHosszMouseClicked
        // TODO add your handling code here:
        Capa c = this.capak.get(this.cbCapak.getSelectedIndex() - 1);
        Double newHossz = Double.parseDouble(this.spHossz.getValue().toString());
        c.setHosszPlus(newHossz / 100);
        this.lblHossz.setText(c.getHossz().toString());
        this.capak.set(this.cbCapak.getSelectedIndex() - 1, c);
        this.spHossz.setVisible(false);
        this.btnMentHossz.setVisible(false);
        this.btnSzerkesztHossz.setVisible(true);
        
    }//GEN-LAST:event_btnMentHosszMouseClicked

    private void btnSzulinapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSzulinapMouseClicked
        // TODO add your handling code here:
        if(Ablak.enabled[this.cbCapak.getSelectedIndex() - 1] == 1){
        Capa c = this.capak.get(this.cbCapak.getSelectedIndex() - 1);
        c.setKorPlus();
        this.capak.set(this.cbCapak.getSelectedIndex() - 1, c);
        this.lblKor.setText(c.getKor().toString());
        this.btnSzulinap.setEnabled(false);
        Ablak.enabled[this.cbCapak.getSelectedIndex() - 1] = 0;
        }
    }//GEN-LAST:event_btnSzulinapMouseClicked

    private void spKcalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spKcalStateChanged
        // TODO add your handling code here:
        if(Integer.parseInt(this.spKcal.getValue().toString()) < 1){
            this.spKcal.setValue(1);
        }
        if(Integer.parseInt(this.spKcal.getValue().toString()) > 100 - this.capak.get(this.cbCapak.getSelectedIndex()).getEnergia()){
            this.spKcal.setValue(100 - this.capak.get(this.cbCapak.getSelectedIndex()).getEnergia());
        }
    }//GEN-LAST:event_spKcalStateChanged

    private void btnEszikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEszikMouseClicked
        // TODO add your handling code here:
        Integer kcal = Integer.parseInt(this.spKcal.getValue().toString());
        this.capak.get(this.cbCapak.getSelectedIndex()).eszik(kcal);
        this.pbEnergia.setValue((Integer.parseInt(this.capak.get(this.cbCapak.getSelectedIndex()).getEnergia().toString())));
     
    }//GEN-LAST:event_btnEszikMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ablak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEszik;
    private javax.swing.JButton btnMentHossz;
    private javax.swing.JButton btnNevMent;
    private javax.swing.JButton btnSzerkeszt;
    private javax.swing.JButton btnSzerkesztHossz;
    private javax.swing.JButton btnSzulinap;
    private javax.swing.JButton btnUdv;
    private javax.swing.JComboBox<String> cbCapak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFaj;
    private javax.swing.JLabel lblHossz;
    private javax.swing.JLabel lblKor;
    private javax.swing.JLabel lblLakhely;
    private javax.swing.JLabel lblNev;
    private javax.swing.JProgressBar pbEnergia;
    private javax.swing.JPanel pnlAblak;
    private javax.swing.JSpinner spHossz;
    private javax.swing.JSpinner spKcal;
    private javax.swing.JTextField txtNevSzerk;
    // End of variables declaration//GEN-END:variables
}
